sudo: required
services:
  - docker

before_install:
  - docker build -t OleksandrNechai:docker-react -f Dockerfile.dev .

script:
  - docker run OleksandrNechai:docker-react npm run test -- --coverage
